### PR TITLE
Added two more books

### PR DESCRIPTION
**Pull request by Ujjwal-Shekhawat**
Added two more books

### CODE REVIEW

**Comment by rigtorp** [comment]
These are very old books. I don't think they are relevant given the massive changes of C++ since 1999.

**Comment by Ujjwal-Shekhawat** [comment]
Yes I agree that they are old books
But they help the reader in understanding the core of the language

**Comment by rigtorp** [comment]
Sure, it's just too overwhelming to put all books in the list. The stackoverflow question already has a comprehensive list: https://stackoverflow.com/questions/388242/the-definitive-c-book-guide-and-list

**Comment by Ujjwal-Shekhawat** [comment]
Kk

**Pull request closed without merging**
