### PR TITLE
Add Boost:UT under Testing

### PR DESCRIPTION
**Pull request by jmafc**
In my humble opinion, Boost:UT is now "the fastest of them all", it doesn't use macros as Catch2 and doctest do (unless you're crazy enough to *want* to use them) and doesn't even require an extra file, e.g., test_main.cpp.

### CODE REVIEW

**Comment by tocic** [comment]
@jmafc There is also a more recent macro-free https://github.com/clean-test/clean-test. It's interesting to compare the runtime with it. BTW, [here](https://github.com/cschreib/snitch#benchmark) is the comparison of ut with Catch2, doctest, and snitch.

**Comment by rigtorp** [comment]
Compilation times for Boost.UT look fantastic!

**Comment by rigtorp** [comment]
I added clean-test too. I like these macro free approaches. It would be even more convenient to write these if we had compile time reflection to generate clean assertion messages.

**Comment by jmafc** [comment]
@rigtorp Unfortunately, I've been disappointed with UT. AFAICT, it doesn't really implement SUBCASE/SECTION a la doctest/catch2, i.e., setup steps are *not* executed prior to each subtest. It seems to depend on setup steps creating immutable objects without external side-effects (it may be a laudable goal, but totally impractical for my use cases).

**Comment by rigtorp** [comment]
Also compile times seems not great with boost.UT.

**Comment by jmafc** [comment]
@rigtorp Noticing the lack of activity, I'm wondering if you're still maintaining awesome-modern-cpp. In any case, `doctest` is looking for maintainer(s) because the original one has moved on and recently someone opened an issue asking how to use `doctest` with C++20 modules. Considering its extensive use of macros and the lack of maintainer, I doubt it's going to happen any time soon. Also, `catch` also had a feature request for modules for over two years, but it recently got closed because of its use of macros. So I guess it's time to take another look at Boost:UT (and clean-test).

**Comment by rigtorp** [comment]
Yes I am!

Not sure what you are asking me to do? catch and doctest are still relevant.

**Comment by jmafc** [comment]
> Not sure what you are asking me to do? catch and doctest are still relevant.

I wasn't really asking you to do anything. Catch2 and GoogleTest are still relevant because evidently they have fairly large user bases. Doctest perhaps may be relevant, but right now it seems like it doesn't have a maintainer. As I see it, the problem with all three is that they use macros and with the advent of C++20 modules, macros are, at the very least, not "modern C++".

Boost:UT and clean-test do not depend on macros and UT documents how to use it with modules (although I have not verified that). Supposedly, the advantage of clean-test over UT is that it can run tests concurrently (again, I haven't checked that out), but if GH stars/forks/watches/contributors are a good indicator, UT is about an order of magnitude more popular.

So, now that CMake has support for modules, if somebody wants to use a testing framework together with modules, it appears that Boost:UT is *the* "contender".

**Comment by rigtorp** [comment]
:+1:  very nice observations!

**Pull request merged**
