### PR TITLE
Add project starter template hjson-cpp-example

### PR DESCRIPTION
**Pull request by trobro**

### CODE REVIEW

**Comment by rigtorp** [comment]
Cool, but seems overly specific and not much documentation.

**Comment by trobro** [comment]
Thanks for having a look. Are there specific areas of documentation that you feel are missing?

Which parts do you feel are overly specific? I think Qt is in a league of its own when it comes to cross-platform GUI C++ applications, but their web page seems mostly geared towards selling their tools and consultantcy services, so I felt the need for a small example app like hjson-cpp-example that can easily be used as a starting point for any GUI C++ app.

Over the years I've seen some often recurring problems in existing GUI applications I've been asked to modify:

* More than one configuration system. Typically settings modified in the GUI would be saved in one way and other settings in another way.
* Default configuration values hidden in various places in the source code.
* Using strings to access configuration values, thus not being protected by the compiler from misspellings or usage of removed keys.
* Windows DLL management. Often each developer would manually have to copy DLL files, or there would be a folder in the repository containing DLL files.
* All work performed on the UI thread, causing the UI to freeze when heavy work is performed.

These are the main points I've tried to provide best practices for in hjson-cpp-example. The official Qt 5 documentation for CMake does not provide a solution for the DLL problem, I've had to dig through source code for that.

**Comment by rigtorp** [comment]
Honestly it's just a trivial CMakeLists.txt file. Any non trivial project would require something much more complicated. Pitchfork is a good example on how to structure a non-trivial project.

**Comment by trobro** [comment]
Ok thanks for your input.

**Pull request closed without merging**
